name: Docker runner
on:
    workflow_dispatch:
jobs:
    bulid:
        name: bulid
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build 
              shell: bash
              run: |
                 curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/orgs/aviavinashkr/actions/runners/generate-jitconfig \
                  -d '{"name":"New runner","runner_group_id":1,"labels":["self-hosted","X64","macOS","no-gpu"],"work_folder":"_work"}' 
            # - name : bulid
            #   env:
            #     GH_TOKEN: ${{ secrets.PAT_TOKEN }}
            #   uses: ./gha-runner/
            #   with:
            #     GitHubToken: "${{ secrets.PAT_TOKEN }}"
            #     GH_OWNER: "aviavinashkr"
            #     GH_REPOSITORY: "docker-runner"

            # - name : config
            #   shell: bash
            #   run: |    
            #     # Create the runner and start the configuration experience
            #     ./config.sh --url https://github.com/aviavinashkr/docker-runner --token ${{ secrets.pat_token }}
            #     # Last step, run it!
            #     ./run.sh
