name: runner
on:
    workflow_dispatch:
jobs:
    bulid:
        name: bulid
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name : bulid
              env:
                GH_TOKEN: ${{ secrets.PAT_TOKEN }}
              shell: bash
              run: |  
                # Create a folder
                mkdir actions-runner && cd actions-runner
                # Download the latest runner package
                curl -o actions-runner-linux-x64-2.313.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.313.0/actions-runner-linux-x64-2.313.0.tar.gz
                # Optional: Validate the hash
                echo "56910d6628b41f99d9a1c5fe9df54981ad5d8c9e42fc14899dcc177e222e71c4  actions-runner-linux-x64-2.313.0.tar.gz" | shasum -a 256 -c
                # Extract the installer
                tar xzf ./actions-runner-linux-x64-2.313.0.tar.gz
                # Create the runner and start the configuration experience
                ./config.sh --url https://github.com/aviavinashkr/docker-runner --token ${{ secrets.PAT_TOKEN }}
                # Last step, run it!
                ./run.sh

            # - name : config
            #   shell: bash
            #   run: |    
            #     # Create the runner and start the configuration experience
            #     ./config.sh --url https://github.com/aviavinashkr/docker-runner --token ${{ secrets.pat_token }}
            #     # Last step, run it!
            #     ./run.sh